mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path
from django.urls import include,re_path
from django.conf.urls import url
from . import views
from .views import *
from django.views.generic import CreateView
from django.views.generic.base import RedirectView
from .views import orders_upload



app_name = 'polls'
urlpatterns = [
    path('orders_upload/', orders_upload, name="orders_upload"),
    path('', views.IndexView.as_view(), name='index'),
    re_path(r'^login/$', LoginView.as_view(), name='login'),
    re_path(r'^logout/$', views.logout, name='logout'),
    re_path(r'^register/$', views.UserFormView.as_view(), name='register'),
    path('orders', views.OrderView.as_view(), name='orders'),
    path('create/order', views.OrderCreateAdmin.as_view(), name='order_create'),
    re_path(r'order_costumer/$', views.OrderCreateCustomer.as_view(), name="order_costumer"),
    path('order_ok', views.OrderDetailView.as_view(), name='order_ok'),
    url(r'inventory/$', views.Inventory.as_view(), name="inventory"),
    url(r'busytime/$', views.BusyTime, name="busytime"),
    url(r'add_product/$', views.ProductCreate.as_view(), name="product-add"),
    url(r'add_part/$', views.PartCreate.as_view(), name="part-add"),
    url(r'add_supplier/$', views.SupplierCreate.as_view(), name="supplier-add"),
    url(r'add_pip/$', views.PipCreate.as_view(), name="pip-add"),
    url(r'add_order/$', views.OrderCreateAdmin.as_view(), name="order-add"),
    url(r'add_components/$', views.ComponentsCreate.as_view(), name="components-add"),
    url(r'add_extras/$', views.ExtrasCreate.as_view(), name="newextra-add"),
    url(r'add_supprice/$', views.SuppriceCreate.as_view(), name="supprice-add"),
    url(r'add_pord/$', views.PorderCreate.as_view(), name="pord-add"),
    url(r'add_porderitem/$', views.PorderitemCreate.as_view(), name="porderitem-add"),
    re_path(r'^adminsite/$', views.AdminView.as_view(), name='adminsite'),
    url(r'^product/details/(?P<pk>[0-9]+)/$', views.ProductDetailView.as_view(), name='product_detail'),
    url(r'product_index/$', views.ProductIndexView.as_view(), name="product_index"),
    url(r'product/(?P<pk>[0-9]+)/$', views.ProductUpdate.as_view(), name="product_update"),
    url(r'product/(?P<pk>[0-9]+)/delete/$', views.ProductDelete.as_view(), name="product_delete"),
    url(r'^order/details/(?P<pk>[0-9]+)/$', views.OrderDetailView.as_view(), name='order_detail'),
    url(r'order_index/$', views.OrderIndexView.as_view(), name="order_index"),
    url(r'order/(?P<pk>[0-9]+)/$', views.OrderUpdateAdmin.as_view(), name="order_update"),
    url(r'order/(?P<pk>[0-9]+)/delete/$', views.OrderDeleteAdmin.as_view(), name="order_delete"),
    url(r'^part/details/(?P<pk>[0-9]+)/$', views.PartDetailView.as_view(), name='part_detail'),
    url(r'part_index/$', views.PartIndexView.as_view(), name="part_index"),
    url(r'part/(?P<pk>[0-9]+)/$', views.PartUpdate.as_view(), name="part_update"),
    url(r'part/(?P<pk>[0-9]+)/delete/$', views.PartDelete.as_view(), name="part_delete"),
    url(r'^pip/details/(?P<pk>[0-9]+)/$', views.PipDetailView.as_view(), name='pip_detail'),
    url(r'pip_index/$', views.PipIndexView.as_view(), name="pip_index"),
    url(r'pip/(?P<pk>[0-9]+)/$', views.PipUpdate.as_view(), name="pip_update"),
    url(r'pip/(?P<pk>[0-9]+)/delete/$', views.PipDelete.as_view(), name="pip_delete"),
    url(r'^supplier/details/(?P<pk>[0-9]+)/$', views.SupplierDetailView.as_view(), name='supplier_detail'),
    url(r'supplier_index/$', views.SupplierIndexView.as_view(), name="supplier_index"),
    url(r'supplier/(?P<pk>[0-9]+)/$', views.SupplierUpdate.as_view(), name="supplier_update"),
    url(r'supplier/(?P<pk>[0-9]+)/delete/$', views.SupplierDelete.as_view(), name="supplier_delete"),
    url(r'^components/details/(?P<pk>[0-9]+)/$', views.ComponentsDetailView.as_view(), name='components_detail'),
    url(r'components_index/$', views.ComponentsIndexView.as_view(), name="components_index"),
    url(r'components/(?P<pk>[0-9]+)/$', views.ComponentsUpdate.as_view(), name="components_update"),
    url(r'components/(?P<pk>[0-9]+)/delete/$', views.ComponentsDelete.as_view(), name="components_delete"),
    url(r'^extras/details/(?P<pk>[0-9]+)/$', views.ExtrasDetailView.as_view(), name='newextra_detail'),
    url(r'extras_index/$', views.ExtrasIndexView.as_view(), name="newextra_index"),
    url(r'extras/(?P<pk>[0-9]+)/$', views.ExtrasUpdate.as_view(), name="newextra_update"),
    url(r'extras/(?P<pk>[0-9]+)/delete/$', views.ExtrasDelete.as_view(), name="newextra_delete"),
    url(r'^supprice/details/(?P<pk>[0-9]+)/$', views.SuppriceDetailView.as_view(), name='supprice_detail'),
    url(r'supprice_index/$', views.SuppriceIndexView.as_view(), name="supprice_index"),
    url(r'supprice/(?P<pk>[0-9]+)/$', views.SuppriceUpdate.as_view(), name="supprice_update"),
    url(r'supprice/(?P<pk>[0-9]+)/delete/$', views.SuppriceDelete.as_view(), name="supprice_delete"),
    url(r'^pord/details/(?P<pk>[0-9]+)/$', views.PorderDetailView.as_view(), name='pord_detail'),
    url(r'pord_index/$', views.PorderIndexView.as_view(), name="pord_index"),
    url(r'pord/(?P<pk>[0-9]+)/$', views.PorderUpdate.as_view(), name="pord_update"),
    url(r'pord/(?P<pk>[0-9]+)/delete/$', views.PorderDelete.as_view(), name="pord_delete"),
    url(r'^porderitem/details/(?P<pk>[0-9]+)/$', views.PorderitemDetailView.as_view(), name='porderitem_detail'),
    url(r'porderitem_index/$', views.PorderitemIndexView.as_view(), name="porderitem_index"),
    url(r'porderitem/(?P<pk>[0-9]+)/$', views.PorderitemUpdate.as_view(), name="porderitem_update"),
    url(r'porderitem/(?P<pk>[0-9]+)/delete/$', views.PorderitemDelete.as_view(), name="porderitem_delete"),
    url(r'^product_results/$', product_index, name="product_search"),
    url(r'^part_results/$', part_index, name="part_search"),
    url(r'^components_results/$', components_index, name="components_search"),
    url(r'^supplier_results/$', supplier_index, name="supplier_search"),
    url(r'^extra_results/$', extra_index, name="extra_search"),
    url(r'^order_results/$', order_index, name="order_search"),
    url(r'^queue_results/$', queue_index, name="queue_search"),
    url(r'^pip_results/$', pip_index, name="pip_search"),
    url(r'^pord_results/$', pord_index, name="pord_search"),
    url(r'^porderitem_results/$', porderitem_index, name="porderitem_search"),
    url(r'^supprice_results/$', supprice_index, name="supprice_search"),
    url(r'queue/(?P<pk>[0-9]+)/$', views.QueueUpdateAdmin.as_view(), name="queue_update"),
    path('contact/', contact, name="contact"),
    url(r'contact_index/$', views.ContactIndexView.as_view(), name="contact_index"),
    url(r'^contact/details/(?P<pk>[0-9]+)/$', views.ContactDetailView.as_view(), name='contact_detail'),
    url(r'^contact_results/$', contact_index, name="contact_search"),
    url(r'^recommend/$', recommend, name="recommend"),

]

mysite/contact/models.py
from django.db import models

# Create your models here.

mysite/polls/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Contact


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = {'title', 'message'}

mysite/contact/views.py
from django.shortcuts import render

# Create your views here.

mysite/polls/views.py
from django.http import HttpResponseRedirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import authenticate, login
from django.urls import reverse
from django.views import generic
from django.views.generic import View
from .models import *
from .forms import UserForm, ContactForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as django_login_view
from django.views.generic import FormView
from django.contrib import auth
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import decorators
from django.utils.decorators import method_decorator
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
#import datetime
from django.db import connection
from datetime import datetime, timedelta
from django.views.generic import TemplateView, DetailView
import matplotlib.pyplot as plt
import threading
from tkinter import *
import math
import csv, io
from django.contrib.auth.decorators import permission_required
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
import smtplib



# from here


class UserFormView(View):
    form_class = UserForm
    template_name = 'polls/registration_form.html'

    # display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process from data
    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            # cleaned (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            # return user objects if details are correct
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('polls:index')

        return render(request, self.template_name, {'form': form})


class LoginView(FormView):
    form_class = AuthenticationForm
    template_name = 'polls/login.html'

    def form_valid(self, form):
        usuario = form.get_user()

        django_login_view(self.request, usuario)
        return redirect('polls:index')

        # return super(LoginView, self).form_valid(form)


# from .models import all  # Choice, Question, Product, Part, Unit
def logout(request):
    auth.logout(request)
    return render(request, 'polls/logout.html')


class Inventory(TemplateView):
    template_name = 'polls/inventory.html'
    context_object_name = 'all_generics'

    def get_context_data(self, *args, **kwargs):
        kaki = " "
        demands=getallPartsDemand()
        context = super(Inventory, self).get_context_data(*args, **kwargs)
        for par in Part.objects.all():
            for dem in demands:
                if(dem[0] == par):
                    today = (datetime.now()).replace(tzinfo=None)
                    #lastOrder = getLatesTakenPorderWithPart(par)
                    #quantity = order 
                    #if(lastOrder == None):
                    #    delta=0
                    #else:  
                    #    delta = (today-lastOrder.porderDate.replace(tzinfo=None)).days
                        #delta=0
                    #nextdate = today + timedelta(days=5)
                    #nextdate = today + timedelta(days=(int((par.lt/30)*(math.sqrt(2*dem[1])))-int(delta))
                    if(dem[1]==0):
                        nextdate = 'no demand'
                    else:
                        nextdate = today+timedelta(days=int((par.stock/(dem[1]/30)-par.lt)))
                        nextdate = datetime.strftime(nextdate, '%d/%m/%Y')

                  
                     
                    kaki += "<td>" + par.pdes +"</td><td>" + str(par.stock) + "</td><td>" + str(dem[1]) + "</td><td>" + str(nextdate) + "</td></tr>"  
        context['parts'] = kaki
       
        
        
        return context


class AdminView(generic.ListView):
    template_name = 'polls/adminsite.html'
    context_object_name = 'all_orders'

    def get_queryset(self):
        return Order.objects.filter(
            Q(ifSupplied=False)
        ).order_by('-orderPick')


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    def get_context_data(self, *args, **kwargs):
        context = super(IndexView, self).get_context_data(*args, **kwargs)
        rec = recommend()
        context['rectwo0'] = str(rec[0][0][0]) + " and " + str(rec[0][0][1]) 
        context['rectwo1'] = str(rec[0][1][0]) + " and " + str(rec[0][1][1]) 
        context['rectwo2'] = str(rec[0][2][0]) + " and " + str(rec[0][2][1]) 
        context['rectwo3'] = str(rec[0][3][0]) + " and " + str(rec[0][3][1]) 
        context['rectwo4'] = str(rec[0][4][0]) + " and " + str(rec[0][4][1]) 
        
        context['recfive0'] = str(rec[1][0][0]) + ", " + str(rec[1][0][1]) + ", " + str(rec[1][0][2]) + ", " + str(rec[1][0][3])+ ", " + str(rec[1][0][4])     
        context['recfive1'] = str(rec[1][1][0]) + ", " + str(rec[1][1][1]) + ", " + str(rec[1][1][2]) + ", " + str(rec[1][1][3])+ ", " + str(rec[1][1][4])
        context['recfive2'] = str(rec[1][2][0]) + ", " + str(rec[1][2][1]) + ", " + str(rec[1][2][2]) + ", " + str(rec[1][2][3])+ ", " + str(rec[1][2][4])
        context['recfive3'] = str(rec[1][3][0]) + ", " + str(rec[1][3][1]) + ", " + str(rec[1][3][2]) + ", " + str(rec[1][3][3])+ ", " + str(rec[1][3][4])
        context['recfive4'] = str(rec[1][4][0]) + ", " + str(rec[1][4][1]) + ", " + str(rec[1][4][2]) + ", " + str(rec[1][4][3])+ ", " + str(rec[1][4][4]) 
        

        return context


    
    def get_queryset(self):
        request = self.request
        user_id = request.user.id
        order_list =Order.objects.filter(user=user_id).order_by('orderPick')
        order_list=order_list.reverse()[:5]
        return order_list


class OrderView(generic.ListView):
    context_object_name = 'all_generics'
    template_name = 'polls/generic_list.html'

    def get_queryset(self):
        return Order.objects.all()


"""DetailsView"""


class ProductDetailView(generic.DetailView):
    model = Product
    template_name = 'polls/product_detail.html'


class ContactDetailView(generic.DetailView):
    model = Contact
    template_name = 'polls/contact_detail.html'


class OrderDetailView(generic.DetailView):
    model = Order
    template_name = 'polls/order_detail.html'


class PartDetailView(generic.DetailView):
    model = Part
    template_name = 'polls/part_detail.html'


class PipDetailView(generic.DetailView):
    model = Pip
    template_name = 'polls/pip_detail.html'


class SupplierDetailView(generic.DetailView):
    model = Supplier
    template_name = 'polls/supplier_detail.html'


class ComponentsDetailView(generic.DetailView):
    model = Components
    template_name = 'polls/components_detail.html'


class ExtrasDetailView(generic.DetailView):
    model = NewExtra
    template_name = 'polls/newextra_detail.html'


class SuppriceDetailView(generic.DetailView):
    model = SupPrice
    template_name = 'polls/supprice_detail.html'


class PorderDetailView(generic.DetailView):
    model = POrder
    template_name = 'polls/pord_detail.html'


class PorderitemDetailView(generic.DetailView):
    model = POrderItem
    template_name = 'polls/porderitem_detail.html'


"""IndexView"""


class ProductIndexView(generic.ListView):
    template_name = 'polls/product_index.html'
    context_object_name = 'all_products'

    def get_queryset(self):
        """Return the last five published questions."""
        return Product.objects.order_by('pdes')


class OrderIndexView(generic.ListView):
    template_name = 'polls/order_index.html'
    context_object_name = 'all_orders'
    paginate_by = 10
    queryset = Order.objects.all()

    def get_queryset(self):
        """Return the last five published questions."""
        return Order.objects.order_by('-orderPick')


class PartIndexView(generic.ListView):
    template_name = 'polls/part_index.html'
    context_object_name = 'all_parts'

    def get_queryset(self):
        """Return the last five published questions."""
        return Part.objects.order_by('pdes')


class ContactIndexView(generic.ListView):
    template_name = 'polls/contact_index.html'
    context_object_name = 'all_contacts'

    def get_queryset(self):
        """Return the last five published questions."""
        return Contact.objects.order_by('time')


class PipIndexView(generic.ListView):
    template_name = 'polls/pip_index.html'
    context_object_name = 'all_pips'

    def get_queryset(self):
        """Return the last five published questions."""
        return Pip.objects.order_by('part__pdes')


class SupplierIndexView(generic.ListView):
    template_name = 'polls/supplier_index.html'
    context_object_name = 'all_suppliers'

    def get_queryset(self):
        """Return the last five published questions."""
        return Supplier.objects.all()


class ComponentsIndexView(generic.ListView):
    template_name = 'polls/components_index.html'
    context_object_name = 'all_componentss'

    def get_queryset(self):
        """Return the last five published questions."""
        return Components.objects.all()


class ExtrasIndexView(generic.ListView):
    template_name = 'polls/newextra_index.html'
    context_object_name = 'all_newextras'

    def get_queryset(self):

mysite/polls/templates/polls/order_detail.html
{% block content %}
{%load staticfiles%}
    <link rel="stylesheet" type="text/css" href="{%static 'polls/style.css' %}"/>
<link rel="stylesheet" type="text/css" href="{%static 'polls/button.css' %}"/>
{% if request.user.is_superuser %}
                <div class="sidenav">
                     <a href="{%url 'polls:adminsite'%}" class="w3-bar-item w3-button">Home Page</a>
                        <div class="w3-dropdown-content w3-bar-block">
                          <a href="{%url 'polls:order_index' %}" class="w3-bar-item w3-button"> Order</a>
                          <a href="{% url 'polls:product_index' %}" class="w3-bar-item w3-button"> Product</a>
                          <a href="{% url 'polls:part_index' %}" class="w3-bar-item w3-button"> Part</a>
                          <a href="{% url 'polls:pip_index' %}" class="w3-bar-item w3-button"> Part to Product</a>
                          <a href="{% url 'polls:components_index' %}" class="w3-bar-item w3-button"> Component</a>
                          <a href="{% url 'polls:newextra_index' %}" class="w3-bar-item w3-button"> Extra</a>
                          <a href="{% url 'polls:supplier_index' %}" class="w3-bar-item w3-button"> Supplier</a>
                          <a href="{% url 'polls:supprice_index' %}" class="w3-bar-item w3-button"> Supplier Price</a>
                          <a href="{% url 'polls:pord_index' %}" class="w3-bar-item w3-button"> Purchase Orders</a>
                          <a href="{% url 'polls:porderitem_index' %}" class="w3-bar-item w3-button"> Purchase Order Items</a>
                            <a href="{% url 'polls:inventory' %}" class="w3-bar-item w3-button"> Inventory</a>
                            <a href="{% url 'polls:busytime' %}" class="w3-bar-item w3-button"> Data Of Busy Time</a>
                            <a href="{% url 'polls:orders_upload' %}" class="w3-bar-item w3-button"> Orders CSV Upload</a>
                            <a href="{% url 'polls:contact_index' %}" class="w3-bar-item w3-button"> Messages</a>
                        </div>
                    <a href="{% url 'polls:login' %}">Logout</a>
                    <a></a><a></a>
                </div>
{%else%}
    <div class="sidenav">
        <a href="{%url 'polls:index'%}">Home Page</a>
        <a href="{% url 'polls:order_costumer' %}">Order</a>
        <a href="{% url 'polls:contact' %}">Contact</a>
        <a href="{% url 'polls:login' %}">logout</a>
    </div>
{%endif%}
{% endblock %}
<div class=main>
    <html>
        <head>
            <meta http-equiv="Content-type" content="text/html; charset=utf-8">
            <meta content="text/html; charset=iso-8859-2" http-equiv="Content-Type">
        </head>
        <style>
            html, body { font-family: "Lato", sans-serif;}
            .form-group {margin-left: 160px; padding: 0px 10px; }
            .main {margin-left: 160px; padding: 0px 10px; }
            .sidenav { 
                height: 100%; width: 170px; position: fixed; z-index: 1; 
                top: 0; left: 0; background-color: #111; 
                overflow-x: hidden; padding-top: 20px;
            }
            .sidenav a { padding: 6px 8px 6px 16px; text-decoration: none; font-size: 20px; color: #818181; display: block; }
            .sidenav a:hover { color: #f1f1f1; }
            h1 { font-family: Arial, Helvetica, sans-serif; font-size:40px; margin-top: 20px; 
            color: #1f1f47; margin-bottom: 10px; 
            }
        </style>
    {% block body %}
<h2 align="center" style="font-size: 60px; font-family:Courier ">Order Detail</h2>
        <h4 style="font-family:Courier" >Guidelines:  Below you may find a specific order details.</h4>
        <h4 style="font-family:Courier">If you would like to make a change in the details, click the "Change" button.</h4>
        {% if request.user.is_superuser %}
            <h2>User:  {{ order.user }}</h2>
        {%endif%}
        <h2>Order Date: {{ order.orderDate }} | Order Pick: {{ order.orderPick }}</h2>
        <h2>Status: {{ order.orderStatus }} | Remarks: {{ order.remarks }}</h2>
        <h2>Product:  {{ order.product1 }}  | Supplied?:  {{ order.ifSupplied }} </h2>
        {% if order.component1 %}
            <h2>Components: {{ order.component1.part }} | {{ order.component2.part }} | {{ order.component3.part }} | {{ order.component4.part }} | {{ order.component5.part }} </h2>
        {%endif%}
        {% if order.extra1 or order.extra2 or order.extra3 %}
            <h2> Extras:  {{ order.extra1.extra_part }} | {{ order.extra2.extra_part }} | {{ order.extra3.extra_part }} </h2>
        {%endif%}
    </html>
</div>
{% if request.user.is_superuser %}
<div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button id="myButton" class="example_b" >Change</button>

        <script type="text/javascript">
            document.getElementById("myButton").onclick = function () {
                location.href ="{% url 'polls:order_update' order.pk %}";
            };
        </script>
        </div>
</div>
{%endif%}
{% endblock %}

mysite/polls/templates/polls/order_index.html
{%load staticfiles%}
<link rel="stylesheet" type="text/css" href="{%static 'polls/style.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{%static 'polls/button.css' %}"/>

{% block content %}
<div class="sidenav">
    <a href="{%url 'polls:adminsite'%}" class="w3-bar-item w3-button">Home Page</a>
                         <div class="w3-dropdown-content w3-bar-block">
                          <a href="{%url 'polls:order_index' %}" class="w3-bar-item w3-button"> Order</a>
                          <a href="{% url 'polls:product_index' %}" class="w3-bar-item w3-button"> Product</a>
                          <a href="{% url 'polls:part_index' %}" class="w3-bar-item w3-button"> Part</a>
                          <a href="{% url 'polls:pip_index' %}" class="w3-bar-item w3-button"> Part to Product</a>
                          <a href="{% url 'polls:components_index' %}" class="w3-bar-item w3-button"> Component</a>
                          <a href="{% url 'polls:newextra_index' %}" class="w3-bar-item w3-button"> Extra</a>
                          <a href="{% url 'polls:supplier_index' %}" class="w3-bar-item w3-button"> Supplier</a>
                          <a href="{% url 'polls:supprice_index' %}" class="w3-bar-item w3-button"> Supplier Price</a>
                          <a href="{% url 'polls:pord_index' %}" class="w3-bar-item w3-button"> Purchase Orders</a>
                          <a href="{% url 'polls:porderitem_index' %}" class="w3-bar-item w3-button"> Purchase Order Items</a>
                          <a href="{% url 'polls:inventory' %}" class="w3-bar-item w3-button"> Inventory</a>
                          <a href="{% url 'polls:busytime' %}" class="w3-bar-item w3-button"> Data Of Busy Time</a>
                          <a href="{% url 'polls:orders_upload' %}" class="w3-bar-item w3-button"> Orders CSV Upload</a>
                          <a href="{% url 'polls:contact_index' %}" class="w3-bar-item w3-button"> Messages</a>
                        </div>
    <a href="{% url 'polls:login' %}">Logout</a>
</div>
{%endblock%}
<div class=main>
    <html>
        <head>
            <meta http-equiv="Content-type" content="text/html; charset=utf-8">
            <meta content="text/html; charset=iso-8859-2" http-equiv="Content-Type">
        </head>
        <style>
            html, body { font-family: "Lato", sans-serif;}
            .form-group {margin-left: 160px; padding: 0px 10px; }
            .main {margin-left: 160px; padding: 0px 10px; }
            .form-inline {margin-left: 160px; padding: 0px 10px; }
            .pagination {margin-left: 160px; padding: 0px 10px; }
            .sidenav {
                height: 100%; width: 170px; position: fixed; z-index: 1;
                top: 0; left: 0; background-color: #111;
                overflow-x: hidden; padding-top: 20px;
            }
            .sidenav a { padding: 6px 8px 6px 16px; text-decoration: none; font-size: 20px; color: #818181; display: block; }
            .sidenav a:hover { color: #f1f1f1; }
            .form-horizontal{margin-left: 160px; padding: 0px 10px; }
            h1 { font-family: Arial, Helvetica, sans-serif; font-size:40px; margin-top: 20px;
                color: #1f1f47; margin-bottom: 10px;
            }
        </style>
        <h2 align="center" style="font-size: 55px; font-family:Courier ">Orders </h2>
<h4 style="font-family:Courier; font-size: 18px">Choose the user from the customer list. Order pick is the requested pickup time by customer.</h4>
<h4 style="font-family:Courier; font-size: 18px">Choose order status from: Waiting/Ready/Take. If the order supplied check the box.</h4>
    </html>
</div>

<div class="form-group" align="center">
        <div class="col-sm-offset-2 col-sm-10">
        <a class="example_b" href="{% url 'polls:order-add' %}"  >Add new Order</a>


        </div>
</div>

    <br>
    <form class="form-inline my-2 my-lg-1" method="GET" action="{% url 'polls:order_search' %}" align="center">

                <input type="text" class="form-control mr-sm-2" name="q" value="{{ request.GET.q }}"
                       placeholder="Search Orders" aria-label="Search">

    </form>
    <ul style=" padding-left:180px;">
            {% for order in all_orders %}<br>
        <geti style="font-size: 18px;"><b>{{ order.get_name }}{{order.get_details}}</b></geti>
<br>
        <a class="example_a" href="{% url 'polls:order_detail' order.pk %}"  rel="nofollow noopener">more details</a>

                <br>
            {% endfor %}
    </ul>
<div class="pagination" align="center">
    <span class="step-links">
                {% if page_obj.has_previous %}
                  <li><a href="?page={{ page_obj.previous_page_number }}">previous;</a></li>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                  <li><a href="?page={{ page_obj.next_page_number }}">next;</a></li>
                {% endif %}
    </span>
</div>